### ISSUE TITLE
web crawler code

### ISSUE THREAD

**Issue by jinwei14** [yuzhounh/Douban-books-2020#1]
I see some book points have been rated down or up. Will you upload the code for the web crawler plz? thanks a lot.

**Comment by yuzhounh** [comment]
See here:
https://github.com/yuzhounh/Douban-books-2020/blob/master/README.md
https://github.com/yuzhounh/Douban-books-crawler-2020

**Comment by yuzhounh** [comment]
> See here:
> https://github.com/yuzhounh/Douban-books-2020/blob/master/README.md
> https://github.com/yuzhounh/Douban-books-crawler-2020

**Comment by yuzhounh** [comment]
> I see some book points have been rated down or up. Will you upload the code for the web crawler plz? thanks a lot.

See here:
https://github.com/yuzhounh/Douban-books-2020/blob/master/README.md
https://github.com/yuzhounh/Douban-books-crawler-2020
